import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Banner from '@/components/layouts/banner'
import '../globals.css'
import Footer from '../../components/layouts/footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',

})

export const metadata: Metadata = {
  title: "Neekko33's Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Banner />
        <div className='max-w-7xl mx-auto pb-8 pt-24'>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
